### ISSUE TITLE
Consider Event::class support

### ISSUE THREAD

**Issue by JanMikes** [contributte/event-application-bridge#1]
Hi, would you consider adding `Event::class` support instead of `Event::NAME`? Or even supporting both methods.

Explanation why it is good is here: https://pehapkari.cz/blog/2017/07/12/the-bulletproof-event-naming-for-symfony-event-dispatcher/

**Comment by f3l1x** [comment]
Well, I don't like that solution. :-) You can easily handle your mentioned behaviour like that:

```php
class EventClassBasedDispatcher implements EventDispatcher
{
	private $mapping = [A\B\C\ApplicationEvent::class => 'application.startup'];

	public function dispatch($name, Event $event) {
		$this->inner->dispatch($this->mapping[get_class($event)], $event);
	}

}
```

Right?

**Comment by JanMikes** [comment]
It is definitely possible. I was just thinking, if you would mind to support such behaviour by default in the package.

I guess it is solved then 😉

**Comment by f3l1x** [comment]
Anyway, thanks for an idea. I appreciate it.
